### ISSUE TITLE
Native Redis Connection Host:Port Compiled to 127.0.0.2:6379

### ISSUE THREAD

**Issue by newzealandpaul** [asmuth/recommendify#3]
The native processor has the redis connection information is hardcoded to 127.0.0.2:6379. This should be configurable from ruby. See recommendify.c line 59.

https://github.com/paulasmuth/recommendify/blob/master/src/recommendify.c#L59

**Comment by asmuth** [comment]
Hey, this was fixed in 0.3.4. Thanks for the report! :)
